server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/subway_route_map_db
    username: root
    password: 1q2w3e4r!
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.naver.com
    port: 465
    username: kim0208yh@naver.com
    password: PEZ89BLWGQBZ
    properties:
      debug: true
      mail:
        smtp:
          ssl:
            enable: true
            #trust: smtp.naver.com
          starttls:
            enable: true
            required: true
          timeout: 5000

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

token:
  secret: subway_project
  expiration_time: 86400000


#    host: smtp.google.com
#    port: 587
#    username: 0chord.mail.tester@gmail.com
#    password: wnktdxzwznmrazez
#    properties:
#      mail:
#        smtp:
#          socketFactory:
#            class: javax.net.ssl.SSLSocketFactory
#          auth: true
#          starttls:
#            enable: true
#          timeout: 5000
